### ISSUE TITLE
Improve documentation in readme 

### ISSUE THREAD

**Issue by Unisay** [zalando/tailor#117]
Disclaimer: I am not a nodejs / frontend developer, so some steps that are apparent for devs working with such stack might not be obvious for me.

So I cloned the repository, walked into this folder and wanted to start basic examples:

# Examples
+ Basic - `node examples/basic`
...
Go to [http://localhost:8080/index](http://localhost:8080/index) after running the specific example.
**Note: Please run the examples with `--harmony` flag for node 4.x versions**

So I've done that:

```bash
ylazaryev@ylazaryev ~/p/tailor> node --harmony examples/basic
/home/ylazaryev/projects/tailor/index.js:17
    const { primary, id } = attributes;
          ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/ylazaryev/projects/tailor/examples/basic/index.js:5:16)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
```
Thanks to @ytanruengsri helped me by saying that I am supposed to run node version 7. 

This is what I suggest to improve first:
*Specify which node versions are supported.*

But thats not the end yet:

```
ylazaryev@ylazaryev ~/p/tailor> node --version
v7.4.0

ylazaryev@ylazaryev ~/p/tailor> node examples/basic
fs.js:558
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/home/ylazaryev/projects/tailor/src/pipe.min.js'
    at Object.fs.openSync (fs.js:558:18)
    at Object.fs.readFileSync (fs.js:468:33)
    at Object.<anonymous> (/home/ylazaryev/projects/tailor/index.js:11:28)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)

ylazaryev@ylazaryev ~/p/tailor> npm test

> node-tailor@2.0.0 test /home/ylazaryev/projects/tailor
> mocha --harmony tests/**

sh: 1: mocha: not found
npm ERR! Test failed.  See above for more details.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?


ylazaryev@ylazaryev ~/p/tailor> npm i mocha --save

lazaryev@ylazaryev ~/p/tailor> npm test

> node-tailor@2.0.0 test /home/ylazaryev/projects/tailor
> mocha --harmony tests/**

module.js:472
    throw err;
    ^

Error: Cannot find module 'nock'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)

ylazaryev@ylazaryev ~/p/tailor> npm i nock --save

```

so after installing 'mocha', 'nock', 'sinon' I have arrived at the same error:

```
lazaryev@ylazaryev ~/p/tailor> npm test

> node-tailor@2.0.0 test /home/ylazaryev/projects/tailor
> mocha --harmony tests/**

fs.js:558
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
```                                                  ^

So the next suggestion would be to *document dependencies needed or how to install them*.

**Comment by Unisay** [comment]
Update: @dazld suggested to do a `npm install` - which helped. Should we put it into the readme?

**Comment by vigneshshanmugam** [comment]
Also regarding the node verisons.. tailor 2.0 supports > node 6.. Will update the docs accordingly

**Comment by vigneshshanmugam** [comment]
addressed it https://github.com/zalando/tailor#examples
