### ISSUE TITLE
Missing pipe.min.js

### ISSUE THREAD

**Issue by stevoPerisic** [zalando/tailor#166]
It seems like a file is missing or the import should be updated to pipe.js, see below:
```
➜  tailor git:(master) ✗ node examples/basic
fs.js:641
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/Users/stevo/tailor/src/pipe.min.js'
    at Error (native)
    at Object.fs.openSync (fs.js:641:18)
    at Object.fs.readFileSync (fs.js:509:33)
    at Object.<anonymous> (/Users/stevo/tailor/index.js:11:28)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
➜  tailor git:(master) ✗ 
```

**Comment by vigneshshanmugam** [comment]
Please do npm install and try running the example. 

`npm install` will trigger the `npm prepublish` after the installation which creates the `pipe.min.js` file.

**Comment by stevoPerisic** [comment]
Just FYI for anyone else that might run into this issue. The cause is the "prepublish" script which, if you run ```sudo npm install```, fails. So to resolve I had to run ```sudo npm install --unsafe-perm``` and that solved it.
